displayName: Header to queryParameter Middleware
type: middleware

import: github.com/dndll/header-to-queryparameter

summary: 'Add a URL query parameter with the value of a given header'

testData:
  header: "X-Version"
  queryParameter: "v"
